# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog de CAFEC170
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Información, tutoriales y aprendizaje de un entusiasta de la Seguridad Informatica.
baseurl:  # the subpath of your site, e.g. /blog en un sitio de usuario queda vacio: 
          # http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/

# --------------------------------------------------------------------------*
# Se debe comentar url para testear localmente (sinó no carga los css)      
url: "cafec170.github.io" # the base hostname & protocol for your site    
# --------------------------------------------------------------------------*


twitter_username: CAFEC170
github_username:  CAFEC170

#Github
repository: "cafec170/CAFEC170.github.io"

# Build settings
markdown: kramdown
theme: minima
